[theme]
primaryColor = "#8BC53F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F7F0"
textColor = "#1B241E"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
enableXsrfProtection = true
